apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  namespace: paperless-ngx
data:
  PAPERLESS_REDIS: "redis://broker:6379"
  PAPERLESS_DBHOST: "db"
  PAPERLESS_TIKA_ENABLED: "1"
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: "http://gotenberg:3000"
  PAPERLESS_TIKA_ENDPOINT: "http://tika:9998"
  USERMAP_UID: "501"
  USERMAP_GID: "20"
  PAPERLESS_TIME_ZONE: "Etc/UTC"
  PAPERLESS_OCR_LANGUAGE: "deu+eng"
  PAPERLESS_SECRET_KEY: "'.N@SLG%eV4R@[Ve,YO}1NN@r6Or70SxsGN,J(^4RV6KoEK7+v;xo1FS_`MJn{HDq'"
  PAPERLESS_ADMIN_USER: "ruben"
  PAPERLESS_ADMIN_PASSWORD: "123"